# Taken from https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy
on:
  push:
    branches:
      - terrain3d
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install and Build 🔧
        run: |
          cd style
          npm install --include=dev
          sed 's/<your MapTiler key>/get_your_own_OpIi9ZULNHzrESv6T2vL/g' configs/config.maptiler.js > config.js
          npm run build
        # MapTiler key get_your_own_OpIi9ZULNHzrESv6T2vL is the MapLibre demo key

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: style/dist/ # The folder the action should deploy.
